spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
#            - , /user-css/**, /user-js/**, /user-media/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
#            - Path=/**
#          , /css/**, /js/**, /media/**
          filters:
            - AuthenticationFilter
#            - RewritePath=/admin/(?<path>.*), /${path}

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**, /logout, /oauth2/**
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**, /categories/**, /variations/**, /discount/**, /search-filter/**, /uploads/**
          filters:
            - AuthenticationFilter


        #        - id: admin-static
        #          uri: lb://ADMIN-SERVICE
        #          predicates:
        #            - Path=/admin/**/*.css
        #            - Path=/admin/**/*.js

        - id: view-store-front
          uri: lb://VIEW-SERVICE
          predicates:
            - Path=/index, 
              /all-categories, 
              /category/**, 
              /product-listing, 
              /product, 
              /contact-us, 
              /about-us, 
              /faq, 
              /privacy-policy, 
              /terms-and-conditions
#          filters:
#            - AuthenticationFilter

        - id: view-auth
          uri: lb://VIEW-SERVICE
          predicates:
            - Path=/sign-in,
              /login,
              /forgot-password,
              /otp-verification,
              /reset-password
#          filters:
#            - AuthenticationFilter

        - id: view-checkout
          uri: lb://VIEW-SERVICE
          predicates:
            - Path=/check-out
#          filters:
#            - AuthenticationFilter

        - id: view-user
          uri: lb://VIEW-SERVICE
          predicates:
            - Path=/user-profile,
              /user-address,
              /user-cart,
              /user-wishlist,
              /user-coupon,
              /user-order,
              /user-wallet
#          filters:
#            - AuthenticationFilter

        - id: view-static
          uri: lb://VIEW-SERVICE
          predicates:
            - Path=/css/**,
              /js/**,
              /media/**
#          filters:
#            - AuthenticationFilter

#        - id: view-service
#          uri: lb://VIEW-SERVICE
#          predicates:
#            - Path >
#          filters:
#            - AuthenticationFilter
  #
  #      globalcors:
  #        corsConfigurations:
  #          '[/**]':
  #            allowedOrigins: "http://localhost:8282"
  #            allowedMethods: "*"
  #            allowedHeaders: "*"

  application:
    name: API-GATEWAY

  server:
    port: 8080

  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: false
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

