spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**, /css/**, /js/**, /media/**
#            - Path=/**
          filters:
            - AuthenticationFilter
#            - RewritePath=/admin/(?<path>.*), /${path}

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**, /logout
          filters:
            - AuthenticationFilter

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**,/categories/**,/variations/**
          filters:
            - AuthenticationFilter



        #        - id: admin-static
        #          uri: lb://ADMIN-SERVICE
        #          predicates:
        #            - Path=/admin/**/*.css
        #            - Path=/admin/**/*.js

        - id: home-service
          uri: lb://HOME-SERVICE
          predicates:
            - Path=/**
          filters:
            - AuthenticationFilter
  #
  #      globalcors:
  #        corsConfigurations:
  #          '[/**]':
  #            allowedOrigins: "http://localhost:8282"
  #            allowedMethods: "*"
  #            allowedHeaders: "*"

  application:
    name: API-GATEWAY

  server:
    port: 8080

  eureka:
    instance:
      hostname: localhost
      prefer-ip-address: false
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

