##------- DISCOUNT -------##

## DISCOUNT COMMAND APIs ##
api.discount.command.post = /discount
api.discount.command.patch = /discount
api.discount.command.delete = /discount

##  DISCOUNT MAPPING APIs ##
api.discount.mapping.post = /discount/mapping

## DISCOUNT QUERY APIs ##
api.discount.query.listing = /discount/listing
api.discount.query.summary = /discount/summary
api.discount.query.mapped-content = /discount/mapped-content

## DISCOUNT ENUM APIs ##
api.discount.enum-api.discount-level = /discount/level
api.discount.enum-api.discount-type = /discount/type
api.discount.enum-api.cap-type = /discount/cap-type
api.discount.enum-api.form-status = /discount/form-status
api.discount.enum-api.summary-status = /discount/summary-status



##------- PRODUCT -------##

## PRODUCT COMMAND APIs ##
api.product.command.post = /product
api.product.command.patch = /product
api.product.command.delete = /product

## PRODUCT QUERY APIs ##

##------- NAVIGATION -------##

api.navigate.page.index = /index
api.navigate.page.dashboard = /admin/dashboard
api.navigate.page.categories = /admin/categories
api.navigate.page.variations = /admin/variations
api.navigate.page.products = /admin/all-products
api.navigate.page.discounts = /admin/discounts
api.navigate.page.coupons = /admin/coupons
api.navigate.page.orders = /admin/orders
api.navigate.page.returns = /admin/returns
api.navigate.page.sales = /admin/sales
api.navigate.page.users = /admin/users
api.navigate.page.blocked-users = /admin/blocked-users
api.navigate.page.subscriptions = /admin/subscriptions
api.navigate.page.news-letters = /admin/news-letters
api.navigate.page.contact-requests = /admin/contact-requests
api.navigate.page.sent-messages = /admin/sent-messages
api.navigate.page.banners = /admin/banners
api.navigate.page.about-us = /admin/about-us