spring.application.name = PRODUCT-SERVICE
server.port = 8986

spring.config.import = optional:classpath:creds.properties
spring.datasource.driver-class-name = org.mariadb.jdbc.Driver

# JPA configuration

spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql = true



## KEEP SQL LOGGING ONLY WHEN DEBUGGING ##
#logging.level.org.hibernate.SQL = DEBUG
#logging.level.org.hibernate.orm.jdbc.bind = TRACE

## PRODUCTION-SAFE ##
spring.jpa.show-sql = false
logging.level.org.hibernate.SQL = OFF
logging.level.org.hibernate.orm.jdbc.bind = OFF



# eureka configuration

eureka.instance.hostname = localhost
eureka.instance.prefer-ip-address = false
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

logging.level.org.springframework.web = DEBUG

# Suppress Eureka heartbeat & registry logs - configuration

logging.level.com.netflix.discovery.shared.transport.jersey = OFF
logging.level.com.netflix.discovery = OFF
logging.level.org.springframework.cloud.netflix.eureka = OFF
logging.level.org.springframework.cloud.client.discovery = OFF
logging.level.org.springframework.web.client.RestTemplate = INFO

#Suppress verbose Eureka HTTP logs

logging.level.org.springframework.web.HttpLogging = INFO

# colored console output configuration

spring.output.ansi.enabled = ALWAYS

##### admin-preference config ########
spring-config-import = classpath:preference-config.yml