#####   filter configurations   #####

### AVAILABLE FILTER TYPES ###
#   - price-range
#   - color
#   - size
#   - stock
#   - pod-available
#   - ## active-status
#   - ## created-at

### AVAILABLE SORT TYPES ###
#   - Newest Arrivals
#   - Name: aA to zZ
#   - Name: zZ to aA
#   - Price: Low to High
#   - Price: High to Low
#   - Stock: Low to High
#   - Stock: High to Low



### filter-types available - for 'user' & 'admin' product listing ###
product.filter.type.user = price-range, colors, size, pod-available
product.filter.type.admin = price-range, colors, size, stock



### filter 'options' available - for specific filter types ###
product.filter.options.price-range = 0 to 499, 500 to 999, 1000 to 1499, 1500 to 2499, 2500 to 3499, 3500 and above
product.filter.options.stock = In Stock, Low Stock, Out of Stock, Overstocked
product.filter.options.pod-available = Available, Not Available



### STOCK RANGE ###
target-inventory-level = 130



# In Stock – Products currently available.
# Low Stock – Products nearing the reorder threshold.
# Out of Stock – No units available.
# Overstocked – Quantity exceeding target inventory levels.
### Backordered – Ordered but not yet received.
# Discontinued – No longer sold or restocked.
# Pre-Order – Available for advance booking.
